[[action]]
# channel is optional
# if `channel` is not found, when react all channel.
channel = "xxxxx"
in      = "test"
out     = "hoge"

[[action]]
channel = "xxxxx"
in      = "aaa.*"
out     = "fuga"

[[action]]
channel = "xxxxx"
in      = "^hoge$"
out     = '''
hello world
hoge
'''